/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const APRRange = IDL.Record({
  'max' : IDL.Float64,
  'min' : IDL.Float64,
});
export const RewardsRate = IDL.Record({
  'miles' : IDL.Opt(IDL.Float64),
  'cashBack' : IDL.Opt(IDL.Float64),
  'points' : IDL.Opt(IDL.Float64),
});
export const CreditCard = IDL.Record({
  'id' : IDL.Nat,
  'apr' : APRRange,
  'categories' : IDL.Vec(IDL.Text),
  'creditScoreRequired' : IDL.Text,
  'annualFee' : IDL.Float64,
  'signupBonus' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'issuer' : IDL.Text,
  'rewardsRate' : RewardsRate,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllCards' : IDL.Func([], [IDL.Vec(CreditCard)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCardsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(CreditCard)], ['query']),
  'getSortedCards' : IDL.Func([IDL.Text], [IDL.Vec(CreditCard)], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const APRRange = IDL.Record({ 'max' : IDL.Float64, 'min' : IDL.Float64 });
  const RewardsRate = IDL.Record({
    'miles' : IDL.Opt(IDL.Float64),
    'cashBack' : IDL.Opt(IDL.Float64),
    'points' : IDL.Opt(IDL.Float64),
  });
  const CreditCard = IDL.Record({
    'id' : IDL.Nat,
    'apr' : APRRange,
    'categories' : IDL.Vec(IDL.Text),
    'creditScoreRequired' : IDL.Text,
    'annualFee' : IDL.Float64,
    'signupBonus' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'issuer' : IDL.Text,
    'rewardsRate' : RewardsRate,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllCards' : IDL.Func([], [IDL.Vec(CreditCard)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCardsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CreditCard)],
        ['query'],
      ),
    'getSortedCards' : IDL.Func([IDL.Text], [IDL.Vec(CreditCard)], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };